# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32972719c893b989a885d28fe5cf7c7f0168d9156f32494b23d1528c5cf3c0929e09be5cfa7b5a54ba7689ae01f2b24b6634c8a2e29e1afaaf775af5780b4002

test:
  secret_key_base: 1619d66aba1a098d90e89d689d38eb89dd375abcd5a44e5ede9deb6e2781f42a7d63b72002eab349c32361eac4ebe78a499e1954d35d01e6b95a26353b4dfe22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
